---
version: "3"

services:
  l7_l7_client_web:
    build:
      context: "./"
      dockerfile: ".docker/production.dockerfile"
    image: "l7_client/web:latest"
    restart: always
    # command: php -welsS [::]:8081 -t public
    command: bash -c "find ./storage/* -type d -exec chmod 777 '{}' \; ; apache2-foreground"
    working_dir: "/var/www/html"
    volumes:
      - ".:/var/www/html"
      - "app:/var/www/html/storage/app/public"
      - "logs:/var/www/html/storage/logs"
      - "cache:/var/www/html/storage/framework/cache"
      - "sessions:/var/www/html/storage/framework/sessions"
      - "views:/var/www/html/storage/framework/views"
    # ports:
    #   - "80:80"
    # expose:
    #   - "80"
    extra_hosts:
      - "local.test:192.168.0.142"
    network_mode: bridge

    env_file:
      - ".env"
    environment:
      docker: "true"
      APP_URL: "http://local.test"
    ### ToDo: Change to your public DNS name
      # LETSENCRYPT_EMAIL: "codeexperts@codeexperts.com.br"
      LETSENCRYPT_HOST: "codeexperts.com.br"
      VIRTUAL_HOST: "local.test"
      VIRTUAL_PORT: 80

    cpu_shares: 128
    mem_reservation: 128m
    mem_limit: 256m
    memswap_limit: -1
    privileged: true
    container_name: "l7_client_web"

volumes:
  app:
    name: l7_client_storage_app
  logs:
    name: l7_client_storage_logs
  cache:
    name: l7_client_storage_cache
  sessions:
    name: l7_client_storage_sessions
  views:
    name: l7_client_storage_views
